# EJ1

In [2]:
import numpy as np
# Nuestra nueva matriz de pruebas, una bidimensional de 5x5
MATRIZ = np.array([
    [4,3,4,3,4],
    [9,8,7,6,5],
    [1,2,3,4,5],
    [7,6,5,6,7],
    [5,4,3,2,1]
])

In [3]:
print ("Primero")
print (MATRIZ[:,1][::-1])
print ("Segundo")
print (MATRIZ[1:,2])
print ("Tercero")
print (MATRIZ[:2, 1:3])
print ("Cuarto")
print (MATRIZ[1:3, :])
print ("Quinto")
print (MATRIZ[:, 1:3][::-1])

Primero
[4 6 2 8 3]
Segundo
[7 3 5 3]
Tercero
[[3 4]
 [8 7]]
Cuarto
[[9 8 7 6 5]
 [1 2 3 4 5]]
Quinto
[[4 3]
 [6 5]
 [2 3]
 [8 7]
 [3 4]]
